server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanbang_db?useSSL=false&serverTimezone=Asia/Shanghai
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 10s
      password: 123123
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # Publisher settings
    publisher-confirm-type: correlated
    publisher-returns: true
    # Listener settings
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 10
        prefetch: 1
  jackson:
    time-zone: Asia/Shanghai
    property-naming-strategy: SNAKE_CASE
sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#  global-config:
#    db-config:
#      id-type: AUTO
springdoc:
  packages-to-scan: com.wanbang.controller


