server:
  port: 8000
spring:
  application:
    name: manager-backend
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/wanbang_db
      username: root
      password: 123123
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3306/wanbang_delivery
      username: root
      password: 123123
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 123123

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
seata:
  enabled: true
  application-id: manager-backend
  tx-service-group: my_test_tx_group
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
